### ISSUE TITLE
Add a 12 h delay

### ISSUE THREAD

**Issue by zekooooo** [nproth/pin#11]
Hi, I love your app, it's awesome!

There's just one thing I'd like to add, an option to snooze the note for 12 hours, since sometimes 6 hours is too short and a whole day is too long.

**Comment by nproth** [comment]
Thanks, I added the 12 hour delay. The update should arrive on F-Droid over the next few days.
Also, you can change the snooze duration in small intervals by dragging the white circle that wraps around the timer-button.
