### ISSUE TITLE
Feature request : make snooze button hitbox bigger

### ISSUE THREAD

**Issue by antznin** [nproth/pin#28]
I might be alone in this issue... but I find myself missing the snooze button (represented by a clock when writing a new note) pretty often. I hit next to it, resulting in quitting the note without saving it.

Making the hitbox slightly bigger would fix the issue, imo.

**Comment by papb** [comment]
Ah, interesting, I didn't even know this feature existed... I used to create the note first and then snoozed it from the notification itself...

I think the hitbox could be increased as well

**Comment by antznin** [comment]
To be clear, the following screenshot shows the button I'm referring to :
![Screenshot_20200225-182032__01](https://user-images.githubusercontent.com/37036499/75271194-cc8c2100-57c9-11ea-94b7-7577b6cc32cf.jpg)
