### ISSUE TITLE
Abandoned?

### ISSUE THREAD

**Issue by dotlineX** [nproth/pin#29]
I use this app near daily and its amazing.

I saw that the dev hasnt done anything on github through all of 2020.

I just hope he/she is okay and would love to support this project.

**Comment by nproth** [comment]
Thank you for your concerns.
While I'd like to eventually continue work on this project, I will not manage to do so in the foreseeable future.

**Comment by dotlineX** [comment]
Thank you for your reply, I love the app, I am happy that you didnt abondon it. I am willing to support the project!

**Comment by nproth** [comment]
Nice to hear that. Thank you for the support offer, but I have no time to spare for the project currently.

**Comment by mizzunet** [comment]
This issue may be closed
