### ISSUE TITLE
Feature: Make notifications persistent

### ISSUE THREAD

**Issue by mizzunet** [nproth/pin#32]
Would solve accidental "Clear All" or clearing by swiping

**Comment by nproth** [comment]
This feature is already implemented. Long pressing the "p!n" button (on the right) should make the notifications persistent. But the user interface isn't exactly intuitive.

**Comment by mizzunet** [comment]
> This feature is already implemented. Long pressing the "p!n" button (on the right) should make the notifications persistent. But the user interface isn't exactly intuitive.

Great, thanks :)
