### ISSUE TITLE
Italian corrections...

### ISSUE THREAD

**Issue by papoloop** [nproth/pin#34]
It's just a little thing...  In the notification area, if I set the reminder to 24 hours, I can postpone it for a day but the string in Italian is not correct because it is presumably taken by the system.  "POSTICIPA 1D" ("SNOOZE 1D") should be "POSTICIPA 1G".  Day -> Giorno.  Minutes and hours are also fine in Italian.
(Same behavior in pop-up notifications when postponed notes are entered.)
If it's a simple thing that doesn't involve a lot of code work it would be appreciated.  Maybe in the next update...  I would also like to correct three strings of the current translation:
"Fissa notifiche" -> "Notifiche bloccate"
"Sblocca notifiche" -> "Notifiche sbloccate"
"Mostra in %" -> "Mostra tra %"

I also noticed that the "SNOOZE" time is set for all notifications from the time setted in the last reminder entered.
Thanks.
![Screenshot_2021-05-01-17-22-02-36~2](https://user-images.githubusercontent.com/82475578/116787428-39710a00-aaa4-11eb-922c-689b8db38da2.jpg)

**Comment by papoloop** [comment]
Line 21
<string name="toast_pin_background">Mostra tra %1$s</string>

Line 25
<string name="toast_fix_pins">Notifiche bloccate</string>

Line 26
<string name="toast_unfix_pins">Notifiche sbloccate</string>

**Comment by papoloop** [comment]
Line 21
`<string name="toast_pin_background">Mostra tra %1$s</string>`

Line 25
`<string name="toast_fix_pins">Notifiche bloccate</string>`

Line 26
`<string name="toast_unfix_pins">Notifiche sbloccate</string>`

**Comment by nproth** [comment]
Thank you very much, it's integrated now. Sorry for the delay.

Regarding the Snooze duration: The slider is intended as a global setting and not specific to individual notifications. I can see that the interface might be confusing. But from a usability standpoint I'd argue that it would be cumbersome to change the Snooze time when it is set for notes individually and the 'Snooze all' function would trigger multiple alarms at the respective snooze times.

**Comment by papoloop** [comment]
Thank you very much.  I love p!n, so simple, so useful, indispensable.  I discovered it by reading a technology magazine.  I am really proud to contribute in some way to the improvement of this app.

**Comment by nproth** [comment]
Nice to hear. It's great seeing that other people care so much about the app, too. May I ask which magazine featured _p!n_? I was not aware of that.

**Comment by papoloop** [comment]
https://gizchina.it/2021/04/migliori-app-android-che-non-trovi-sul-play-store/
