### ISSUE TITLE
feature request: more delay intervals or custom interval

### ISSUE THREAD

**Issue by petep0p** [nproth/pin#35]
i love this app and make constant use of it to keep from making myself look like an idiot by forgetting things. 

one thing i would love to see is either more choices for the delay interval or the option to set a custom delay time. i frequently find myself wanting to delay something longer than an hour but less than three hours, or more than 3 but less than 6, for example. just adding a bunch more at 30 min intervals, or even at 1hr intervals would suffice, but the best would be the ability to set a custom delay. 

thanks for putting this software together! it's one of my favorite things about my phone now.

**Comment by nproth** [comment]
Great to hear! I'm not sure whether that's exactly what you want, but you can adjust the delay with the slider around the button. The button itself sets the maximum value of the slider to allow for a more coarse / fine-grained control.
![Screenshot_1622279026](https://user-images.githubusercontent.com/48482306/120064879-c771ed80-c06e-11eb-8e46-b696eb7703ac.png)

**Comment by papoloop** [comment]
Cool!  It wasn't written anywhere and I would never be able to find out ... Thanks.  Perhaps a more detailed user guide would be needed.  Are you interested in an Italian translation of the user guide?

**Comment by nproth** [comment]
I just documented the slider in the project README. There is currently no user guide for the app apart from what was contributed to the README by artfulrobot. I feel that the README, as the main documentation of the project, should remain English.

While not the place for a full user guide, you could translate the F-Droid app description, if you'd like. It resides in the 'fastlane' folder in the language specific files 'full_documentation.txt' and 'short_documentation.txt'. It might also be a great start to learn about git, if you are interested in that.

**Comment by papoloop** [comment]
👍 Oki

**Comment by nproth** [comment]
So the general workflow is to fork the repository and then use git to clone your fork to your computer, add, commit, and push the files to your fork and then create a pull request to this repository. If you are not comfortable with that, you can also paste the files here.

**Comment by papoloop** [comment]
I am stuck in bed for a month due to a broken leg ... I am doing everything on my smartphone and I see it a little complex now.  It will be for next time, I will try to learn something new.  Let's do that today I copy the files ...

**Comment by papoloop** [comment]
Appunta le note nell'area di notifica.

**Comment by papoloop** [comment]
`Un'app minimalista per scrivere note da mostrare come promemoria nell'area di notifica del telefono::

<ul>
<li>Scrivi le tue note e salvale come notifiche</li>
<li>Modifica le tue note</li>
<li>Elimina le tue note</li>
<li>Nascondi le tue note per un periodo di tempo specifico</li>
</ul>

L'app è stata progettata tenendo conto delle linee guida del <b>Material Design</b>.

Le note create vengono salvate nel database dell'app e verranno mostrate nuovamente anche dopo un riavvio del telefono. (Verificare che le impostazioni di risparmio energetico del sistema permettano all'app di funzionare in background)`

**Comment by petep0p** [comment]
that's been there this whole time?! that is exactly what i want and probably would have been an obvious to anyone younger than me. thanks for responding!

**Comment by nproth** [comment]
> I am stuck in bed for a month due to a broken leg... I am doing everything on my smartphone and I see it a little complex now. It will be for next time, I will try to learn something new. Let's do that today I send you the files...
> 
> [Short.txt](https://github.com/nproth/pin/files/6566507/Short.txt)
> [Full.txt](https://github.com/nproth/pin/files/6566511/Full.txt)
> 
> Sorry, the names are incorrect, I shortened them for convenience.

Oh, I'm sorry to hear that. Yes, smartphones are really not made for this kind of work. Thank you for the translation anyway. I put the files in the repository and I *hope* that F-Droid picks them up as well. It will after the next app update at the latest. I hope you get well soon!

**Comment by nproth** [comment]
> that's been there this whole time?! that is exactly what i want and probably would have been an obvious to anyone younger than me. thanks for responding!

I think that doesn't have much to do with age, it might just be a problem of the interface, which is not very discoverable.
