### ISSUE TITLE
Incorrect position of the "three dots" in the text action menu

### ISSUE THREAD

**Issue by di72nn** [nproth/pin#38]
The button that opens the overflow menu in the text action menu is slightly offset. Same issue with the arrow button that closes that menu.

Screenshots from an Android 9 emulator:

Actual layout | Expected layout
--- | ---
![Screenshot_1630756234](https://user-images.githubusercontent.com/1114779/132093594-c5535e57-7294-4495-afb5-146dc8d57ebb.png) | ![Screenshot_1630756248](https://user-images.githubusercontent.com/1114779/132093602-273311eb-4847-478c-bd46-7ebc48722748.png)
![Screenshot_1630756236](https://user-images.githubusercontent.com/1114779/132093606-feadb176-a730-435d-90fb-2a00d33b168b.png) | ![Screenshot_1630756250](https://user-images.githubusercontent.com/1114779/132093613-6948f2ea-d01b-45db-9b66-f16075b91b6c.png)

Some experimentation showed that removing `<item name="android:fitsSystemWindows">true</item>` from `values-v19/styles.xml` solves the problem with the menu (but draws the UI under the on-screen keyboard; also removing `android:windowTranslucentStatus` produces the result under "Expected layout"). I'm not very good with Android UI so I didn't investigate any further.

This may not look like a serious issue, but it makes it much harder to open the overflow menu to reach the "Select all" action.

Thanks for developing the app!

**Comment by nproth** [comment]
Thank you, also for hunting the cause down. I think I have solved it, but I'm not very good with Android UI either ;)
