### ISSUE TITLE
50 note limit

### ISSUE THREAD

**Issue by heyheyhello** [nproth/pin#44]
Hi Nils,

I've been using p!n for a few years, it's a great minimal app! I usually add some quick notes while I'm out and then eventually transcribe them to a large note app/system and clear the queue... usually this is only 7-10 items. However, last week was busy and I ended up jotting down a lot of things, and noticed the stops creating notes after 50 items.

I understand as a minimal app it might be out of its intended usecase, but in the very least I was hoping for an error or an explicit notification like _"You're overusing this app; get a notebook."_. Instead it silently fails to create new notes. I think I lost a bit data from this...

I can't see any explicit limit in https://github.com/nproth/pin/blob/master/app/src/main/java/de/nproth/pin/NotesProvider.java so I'm not sure why it's happening. I've reproduced this on two Android phones (Essential PH1 & LG K20).

Is this a bug? Or if this is a feature can it be described, at least in the app description to prevent people from losing data.

Video:

https://user-images.githubusercontent.com/44614862/153734874-0cab08cf-208e-435b-b982-cad4580a97f0.mp4

Thanks!

**Comment by nproth** [comment]
Hi Hames,
thank you. Android seems to have a restriction on how many notifications an app can display simultaneously. The app itself has no limit on how many notes you can create and all your notes should still be stored in its database. Try snoozing or deleting newer notes (after transcribing them) and the old ones should reappear. Long pressing the timer button on the left unsnoozes all notes, which might come in handy in the process.
I regularly run into this limit and never experienced data loss. However, the notes might reappear in a different order than expected. I sincerely hope you'll find your notes again this way.

**Comment by heyheyhello** [comment]
I finally moved notes over last night and yes - they came back as soon as there was room in the notification area. No data loss.

I figured things would be fine after reading the code too since I trust SQLite to be safe. All good. Thanks for the reply and the wonderful app!
