### ISSUE TITLE
[Request] Option to hide the icon in Status bar and notification from lockscreen

### ISSUE THREAD

**Issue by chilliger** [nproth/pin#6]
It would be nice to have a option to hide the app icon in the status bar. You only see the notes when you drop down the notification panel so the status bar doesn't get cluttered. Also hidding the notification from the lockscreen would be nice. I do not know if it is possible to implement this through the native app notification settings. What do you think?

**Comment by nproth** [comment]
On newer versions Android allows you to hide notifications on  the lock screen on a per-app basis. You can find the settings under _Apps_ > _p!n_ > _Notifications_ in your Settings-App. Or you can long-click p!n's notification and then - depending on your version of Android - select _more settings_ or a small info icon.

On Android 8.0+ you will see two so-called _Notification Channels_ labelled _Newly added notes_ and _Wake up alert_ instead. You should leave them enabled in order for p!n to work properly but when you select them you can set lock screen accessibility and visual intrusion individually. When you change _Behaviour_ to _Show silently and minimize_ the status bar icon will disappear but then you will not receive any alerts from notes as they are posted to the second channel when they wake up and behave according to its settings.

Hiding the status bar icon without affecting the notifications priority is only possible through a 'hack': The app could provide an empty notification icon but it would eat up the same space as visible ones and would clutter the status bar all the same.

**Comment by chilliger** [comment]
@nproth sorry for answering this late.
Are those notfication settings you are talking about present in Android 8? I don't have a _Behaviour_ setting there:
<img src="https://user-images.githubusercontent.com/2310896/57451286-259dbf00-7261-11e9-9268-f8d74547bcb4.png" width="250">

The closed source app [Notable](https://play.google.com/store/apps/details?id=com.icechen1.notable&hl=en) provides settings to do so:
<img src="https://user-images.githubusercontent.com/2310896/57451769-7e218c00-7262-11e9-8302-b623447f8e55.png" width="250">
<img src="https://user-images.githubusercontent.com/2310896/57451934-ce98e980-7262-11e9-8e73-bd54f7794a0b.png" width="250">
<img src="https://user-images.githubusercontent.com/2310896/57451964-e1132300-7262-11e9-9bc4-4cbb4129cfb9.png" width="250">

**Comment by nproth** [comment]
Yes, on your first screenshot you can click on _Newly added Notes_ and _Wake up alert_, not the adjacent Switches but on the labels themselves. This will bring up additional settings, specifically whether p!n's notifications are shown on the lock screen and with which priority those notifications are displayed. There you can change _On the lock screen_ to _Don't show notifications at all_ to hide notes on your lock screen. Also, setting _Importance_ to _Low_ will hide the status bar icon - with the side effects mentioned above.

**Comment by chilliger** [comment]
Ah I see. I think I like your implementation better because it is based on native android settings. I can work with that. Thanks. Your is going to replace the one from the play store now 👍
